site_name: "curiosityworks.org"
copyright: curiosityworks.org
repo_url: https://github.com/curiosinauts/site
edit_uri: edit/main/docs/
site_dir: site

nav:
  - 'index.md'
  - 'student_computer_setup.md'
  - 'vscode_over_web.md'
  - 'Senior Lessons':
    - 'senior/lesson1.md'
    - 'senior/lesson2.md'
    - 'senior/lesson3.md'
    - 'senior/lesson4.md'
    - 'senior/lesson5.md'
    - 'senior/lesson6.md'
  - 'Junior Lessons':
    - 'junior/lesson5.md'
  # - Commands:
  #   - get:
  #     - 'commands/host/host-ip.md'
  #     - 'commands/host/host-port.md'
  #     - 'commands/get/build.md'
  #     - 'commands/get/pybuild.md'
    # - register:
    #   - 'commands/service.md'
  # - Foo:
  #     - "foo/index.md"

theme:
  name: material
  language: en
  # favicon: images/favicon-pplus-32x32.png
  icon:
    repo: fontawesome/brands/github
  # logo: images/paramount_icon_logo_white-cropped.gif
  palette:
    - media: "(prefers-color-scheme: light)"
      # scheme: paramount-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - content.code.annotate
    - content.tabs.link
  #   - navigation.tabs
  #   - navigation.tabs.sticky

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true